[Settings]
# Added automatically by the Netlify CLI. It has no effect during normal 
# Git-backed deploys.
ID = "54905551-2647-464a-aaf7-52dca9f84776"
[[redirects]]
  from = "/Callback"
  to = "/Callback"